DESENVOLVER UM ALGORITMO DE REDES NEURAIS ARTFICIAIS DE REGRESSÃO : 

- De acordo com os resultados abaixo o algoritmo com o escalonamento dos previsores foi o que obteve o melhor desempenho com 86.77 % e o sem fazer o escalonamento deu 75.71 %

Sendo assim o algoritmo de RNA de Regressão com previsores escalonado foi o que obteve o melhor desempenho

In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv('insurance.csv', sep=',' , encoding='iso-8859-1')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder

df.iloc[:,1] = LabelEncoder().fit_transform(df.iloc[:,1])
df.iloc[:,4] = LabelEncoder().fit_transform(df.iloc[:,4])
df.iloc[:,5] = LabelEncoder().fit_transform(df.iloc[:,5])

In [8]:
df.head(20)

age sex     bmi  children smoker region      charges
0    19   0  27.900         0      1      3  16884.92400
1    18   1  33.770         1      0      2   1725.55230
2    28   1  33.000         3      0      2   4449.46200
3    33   1  22.705         0      0      1  21984.47061
4    32   1  28.880         0      0      1   3866.85520
5    31   0  25.740         0      0      2   3756.62160
6    46   0  33.440         1      0      2   8240.58960
7    37   0  27.740         3      0      1   7281.50560
8    37   1  29.830         2      0      0   6406.41070
9    60   0  25.840         0      0      1  28923.13692
10   25   1  26.220         0      0      0   2721.32080
11   62   0  26.290         0      1      2  27808.72510
12   23   1  34.400         0      0      3   1826.84300
13   56   0  39.820         0      0      2  11090.71780
14   27   1  42.130         0      1      2  39611.75770
15   19   1  24.600         1      0      3   1837.23700
16   52   0  30.780         1      0      0  10797.33620
17   23   1  23.845         0      0      0   2395.17155
18   56   1  40.300         0      0      3  10602.38500
19   30   1  35.300         0      1      3  36837.46700

In [9]:
independente = df.iloc[:, 0:6].values
independente

array([[19, 0, 27.9, 0, 1, 3],
       [18, 1, 33.77, 1, 0, 2],
       [28, 1, 33.0, 3, 0, 2],
       ...,
       [18, 0, 36.85, 0, 0, 2],
       [21, 0, 25.8, 0, 0, 3],
       [61, 0, 29.07, 0, 1, 1]], dtype=object)

In [10]:
dependente = df.iloc[:, 6:7].values
dependente

array([[16884.924 ],
       [ 1725.5523],
       [ 4449.462 ],
       ...,
       [ 1629.8335],
       [ 2007.945 ],
       [29141.3603]])

In [11]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

In [12]:
x_teste.shape

(402, 6)

In [13]:
y_teste.shape

(402, 1)

In [14]:
x_treino.shape

(936, 6)

In [15]:
y_treino.shape

(936, 1)

In [44]:
from sklearn.neural_network import MLPRegressor

redes = MLPRegressor(hidden_layer_sizes=(100, 100), activation='relu', verbose=True, max_iter=2000,
                    solver='adam', random_state = 12)

In [45]:
redes.fit(x_treino, y_treino)

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 157868476.30849880
Iteration 2, loss = 157718841.78345600
Iteration 3, loss = 157559785.80776778
Iteration 4, loss = 157383961.45299137
Iteration 5, loss = 157169241.24367821
Iteration 6, loss = 156915894.15898386
Iteration 7, loss = 156616732.75624901
Iteration 8, loss = 156265122.34124631
Iteration 9, loss = 155841706.28115329
Iteration 10, loss = 155338568.81365284
Iteration 11, loss = 154736399.16602743
Iteration 12, loss = 154035363.87105501
Iteration 13, loss = 153208213.75087458
Iteration 14, loss = 152259521.69140112
Iteration 15, loss = 151179304.56249869
Iteration 16, loss = 149908243.63424614
Iteration 17, loss = 148524380.43025383
Iteration 18, loss = 146903830.76711762
Iteration 19, loss = 145151788.14186198
Iteration 20, loss = 143211346.04597604
Iteration 21, loss = 141063108.33203861
Iteration 22, loss = 138682599.81369826
Iteration 23, loss = 136114288.49876973
Iteration 24, loss = 133378368.84461215
Iteration 25, loss = 130467374.31719677
Iteration

MLPRegressor(hidden_layer_sizes=(100, 100), max_iter=2000, random_state=12,
             verbose=True)

In [46]:
redes.n_layers_

4

In [47]:
redes.score(x_treino, y_treino)

0.7551078125444582

In [48]:
# Teste

redes.score(x_teste, y_teste)

0.80604081123409

In [49]:
previsoes_teste_rna = redes.predict(x_teste)

In [50]:
# Métricas

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste_rna)

3716.2593200138494

In [51]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste_rna))

5561.525697647288

In [52]:
# Validação Cruzada 

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [53]:
# Separando os dados em folds

kfold = KFold(n_splits = 12, shuffle=True, random_state = 5)

In [54]:
# Criando o modelo
from sklearn.neural_network import MLPRegressor
modelo_rna = MLPRegressor(hidden_layer_sizes=(100, 100), activation='relu', verbose=True, max_iter=2000,
                    solver='adam', random_state = 12)
resultado_rna = cross_val_score(modelo_rna, independente, dependente, cv = kfold)


c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 162862373.70049301
Iteration 2, loss = 162650336.95563129
Iteration 3, loss = 162403198.66984126
Iteration 4, loss = 162096678.14065665
Iteration 5, loss = 161704343.33643734
Iteration 6, loss = 161202207.70203951
Iteration 7, loss = 160568925.58392340
Iteration 8, loss = 159741697.96346575
Iteration 9, loss = 158724871.00218970
Iteration 10, loss = 157463462.04746535
Iteration 11, loss = 155912912.07729688
Iteration 12, loss = 154097458.68348384
Iteration 13, loss = 151941221.27221704
Iteration 14, loss = 149434550.56044257
Iteration 15, loss = 146588343.70269480
Iteration 16, loss = 143328960.43626085
Iteration 17, loss = 139617836.21435502
Iteration 18, loss = 135630266.03900093
Iteration 19, loss = 131258401.64195898
Iteration 20, loss = 126516118.63940333
Iteration 21, loss = 121394129.50797260
Iteration 22, loss = 116051440.14241384
Iteration 23, loss = 110625918.70239821
Iteration 24, loss = 104984343.05876391
Iteration 25, loss = 99588863.38824986
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 11, loss = 155749399.15937206
Iteration 12, loss = 154013738.72325638
Iteration 13, loss = 151993305.44060555
Iteration 14, loss = 149592755.84375378
Iteration 15, loss = 146835017.40123782
Iteration 16, loss = 143666306.64787847
Iteration 17, loss = 140117619.43107352
Iteration 18, loss = 136113771.23105857
Iteration 19, loss = 131670877.63025382
Iteration 20, loss = 126931791.58813216
Iteration 21, loss = 121929180.88261583
Iteration 22, loss = 116562974.25219761
Iteration 23, loss = 111072121.10608348
Iteration 24, loss = 105498565.65305324
Iteration 25, loss = 100175758.96527250
Iteration 26, loss = 94723197.47322029
Iteration 27, loss = 89929201.69623345
Iteration 28, loss = 85191048.16843040
Iteration 29, loss = 81080598.87650008
Iteration 30, loss = 77171700.81996460
Iteration 31, loss = 73771475.45906825
Iteration 32, loss = 71258207.61232708
Iteration 33, loss = 69205862.51457278
Iteration 34, loss = 67833398.14875393
Iteration 35, loss = 66716396.89504243
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 8, loss = 158159634.77266160
Iteration 9, loss = 157166016.86515579
Iteration 10, loss = 155970283.74412906
Iteration 11, loss = 154449516.21449775
Iteration 12, loss = 152688367.18590650
Iteration 13, loss = 150566971.48595834
Iteration 14, loss = 148181880.87687355
Iteration 15, loss = 145413454.60286298
Iteration 16, loss = 142246390.16256148
Iteration 17, loss = 138757123.32198521
Iteration 18, loss = 134757878.64684367
Iteration 19, loss = 130556849.22058944
Iteration 20, loss = 125911056.23396565
Iteration 21, loss = 121140053.08083951
Iteration 22, loss = 115953299.63562937
Iteration 23, loss = 110631808.22970033
Iteration 24, loss = 105150287.34274855
Iteration 25, loss = 99735745.62772195
Iteration 26, loss = 94285100.33817878
Iteration 27, loss = 89243310.17133293
Iteration 28, loss = 84547935.51114801
Iteration 29, loss = 80254535.53138575
Iteration 30, loss = 76495221.36383696
Iteration 31, loss = 73408443.29113135
Iteration 32, loss = 71047855.49457099
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 7, loss = 160140660.61483914
Iteration 8, loss = 159338580.84796423
Iteration 9, loss = 158350717.56364977
Iteration 10, loss = 157092864.08530334
Iteration 11, loss = 155574488.39061466
Iteration 12, loss = 153787584.16154677
Iteration 13, loss = 151611754.40676221
Iteration 14, loss = 149110070.32174659
Iteration 15, loss = 146278127.55998585
Iteration 16, loss = 143020371.85792118
Iteration 17, loss = 139350760.00162363
Iteration 18, loss = 135363115.93452317
Iteration 19, loss = 130931330.56643142
Iteration 20, loss = 126218748.62801433
Iteration 21, loss = 121172729.56045438
Iteration 22, loss = 115950170.62971184
Iteration 23, loss = 110494350.28611398
Iteration 24, loss = 105059530.46141988
Iteration 25, loss = 99538011.59792866
Iteration 26, loss = 94285519.33724254
Iteration 27, loss = 89409667.04406293
Iteration 28, loss = 84915546.30748859
Iteration 29, loss = 80700168.73320095
Iteration 30, loss = 76812027.74956399
Iteration 31, loss = 73823900.15526928
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 11, loss = 154071456.40210921
Iteration 12, loss = 152304276.02861589
Iteration 13, loss = 150223625.38929257
Iteration 14, loss = 147811180.31781188
Iteration 15, loss = 145033128.84223387
Iteration 16, loss = 141898304.88167375
Iteration 17, loss = 138363587.23333246
Iteration 18, loss = 134509916.98429438
Iteration 19, loss = 130242744.36177626
Iteration 20, loss = 125675979.20657605
Iteration 21, loss = 120772894.75496568
Iteration 22, loss = 115457808.81241828
Iteration 23, loss = 110060363.97816619
Iteration 24, loss = 104604573.95234080
Iteration 25, loss = 99326540.66039003
Iteration 26, loss = 93936028.11125651
Iteration 27, loss = 89034873.63371767
Iteration 28, loss = 84336904.72563221
Iteration 29, loss = 80157813.95054190
Iteration 30, loss = 76482869.16653125
Iteration 31, loss = 73355738.09746791
Iteration 32, loss = 70780285.69032183
Iteration 33, loss = 68796241.58369780
Iteration 34, loss = 67284568.35934117
Iteration 35, loss = 66426072.88581423
Iteration 3

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 4, loss = 162397928.08105418
Iteration 5, loss = 162008266.04097664
Iteration 6, loss = 161511907.69612026
Iteration 7, loss = 160876659.80015561
Iteration 8, loss = 160061802.93195599
Iteration 9, loss = 159040696.94572031
Iteration 10, loss = 157789775.32585379
Iteration 11, loss = 156259135.59914899
Iteration 12, loss = 154431475.87797561
Iteration 13, loss = 152241499.76643664
Iteration 14, loss = 149757423.17596444
Iteration 15, loss = 146902477.82880661
Iteration 16, loss = 143651891.16224793
Iteration 17, loss = 139932018.45223296
Iteration 18, loss = 135960531.35199669
Iteration 19, loss = 131433072.86956991
Iteration 20, loss = 126676192.10607569
Iteration 21, loss = 121520732.87597615
Iteration 22, loss = 116258008.15911862
Iteration 23, loss = 110939132.40034480
Iteration 24, loss = 105381143.04317312
Iteration 25, loss = 99947927.42558655
Iteration 26, loss = 94583009.89470899
Iteration 27, loss = 89626824.24024643
Iteration 28, loss = 84824649.23825419
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 7, loss = 158941943.31302896
Iteration 8, loss = 158153914.95462695
Iteration 9, loss = 157179975.87013915
Iteration 10, loss = 155979988.84695321
Iteration 11, loss = 154517202.13668546
Iteration 12, loss = 152731440.10217652
Iteration 13, loss = 150645408.74542844
Iteration 14, loss = 148207870.62368661
Iteration 15, loss = 145369011.83504820
Iteration 16, loss = 142195990.36477435
Iteration 17, loss = 138615285.17511994
Iteration 18, loss = 134679039.44631785
Iteration 19, loss = 130307156.07948066
Iteration 20, loss = 125612612.67687118
Iteration 21, loss = 120506291.01550691
Iteration 22, loss = 115261048.90608843
Iteration 23, loss = 109876446.00875640
Iteration 24, loss = 104213213.45350923
Iteration 25, loss = 98922272.86635700
Iteration 26, loss = 93580248.44541292
Iteration 27, loss = 88553045.21696876
Iteration 28, loss = 84094721.26815853
Iteration 29, loss = 79708427.75144692
Iteration 30, loss = 76148419.53222595
Iteration 31, loss = 72982571.01476242
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 161754892.38029912
Iteration 2, loss = 161540704.26659998
Iteration 3, loss = 161299482.56553867
Iteration 4, loss = 160992378.48698583
Iteration 5, loss = 160607327.45492160
Iteration 6, loss = 160107290.20142466
Iteration 7, loss = 159479846.30838329
Iteration 8, loss = 158663989.63716665
Iteration 9, loss = 157654531.83089951
Iteration 10, loss = 156397957.89002997
Iteration 11, loss = 154895904.81373161
Iteration 12, loss = 153042819.29925191
Iteration 13, loss = 150884896.82243943
Iteration 14, loss = 148380673.68369129
Iteration 15, loss = 145451604.98045406
Iteration 16, loss = 142149289.94397303
Iteration 17, loss = 138468683.91349673
Iteration 18, loss = 134391483.32766774
Iteration 19, loss = 129986453.56513090
Iteration 20, loss = 125168342.18093950
Iteration 21, loss = 120168764.24832205
Iteration 22, loss = 114854621.32628743
Iteration 23, loss = 109514661.19887295
Iteration 24, loss = 104124495.76641873
Iteration 25, loss = 98817740.87188469
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 7, loss = 156439605.52751637
Iteration 8, loss = 155667726.74905646
Iteration 9, loss = 154722580.44199389
Iteration 10, loss = 153524822.01192901
Iteration 11, loss = 152098915.69696203
Iteration 12, loss = 150360259.80031863
Iteration 13, loss = 148291301.14718258
Iteration 14, loss = 145901831.06886229
Iteration 15, loss = 143106575.39907664
Iteration 16, loss = 140041977.23548374
Iteration 17, loss = 136461018.60217473
Iteration 18, loss = 132601113.01945628
Iteration 19, loss = 128329618.13220437
Iteration 20, loss = 123789262.09760745
Iteration 21, loss = 118894541.55829996
Iteration 22, loss = 113797077.28551814
Iteration 23, loss = 108672660.76970521
Iteration 24, loss = 103211968.63019107
Iteration 25, loss = 97922777.34815769
Iteration 26, loss = 92726124.91353577
Iteration 27, loss = 87809072.46269596
Iteration 28, loss = 83311516.55714540
Iteration 29, loss = 79122716.91752495
Iteration 30, loss = 75560093.39492707
Iteration 31, loss = 72401825.59624034
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 8, loss = 155952062.01713306
Iteration 9, loss = 154956324.75972492
Iteration 10, loss = 153730252.15073243
Iteration 11, loss = 152220829.33996549
Iteration 12, loss = 150423212.37593454
Iteration 13, loss = 148285006.25702152
Iteration 14, loss = 145772896.72364956
Iteration 15, loss = 142924559.05652288
Iteration 16, loss = 139728214.85280371
Iteration 17, loss = 136097462.52135924
Iteration 18, loss = 132125248.43389137
Iteration 19, loss = 127768692.54072583
Iteration 20, loss = 123038502.24098720
Iteration 21, loss = 117924287.08048572
Iteration 22, loss = 112750395.09002198
Iteration 23, loss = 107251517.93992369
Iteration 24, loss = 101830314.26622593
Iteration 25, loss = 96516233.65943867
Iteration 26, loss = 91178523.35133341
Iteration 27, loss = 86346529.62384880
Iteration 28, loss = 81827461.31033266
Iteration 29, loss = 77851988.83586971
Iteration 30, loss = 74413410.15762934
Iteration 31, loss = 71608205.69746445
Iteration 32, loss = 69330594.93744585
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 161601625.63964322
Iteration 2, loss = 161387416.18858126
Iteration 3, loss = 161142549.55052096
Iteration 4, loss = 160833520.78470957
Iteration 5, loss = 160446759.18612322
Iteration 6, loss = 159965765.50347546
Iteration 7, loss = 159335206.61020768
Iteration 8, loss = 158548135.34700373
Iteration 9, loss = 157558745.75139141
Iteration 10, loss = 156319901.20919827
Iteration 11, loss = 154829502.83603886
Iteration 12, loss = 153011171.37828022
Iteration 13, loss = 150902583.54290459
Iteration 14, loss = 148371071.01231369
Iteration 15, loss = 145479243.82938311
Iteration 16, loss = 142201111.96206757
Iteration 17, loss = 138509507.90758911
Iteration 18, loss = 134478622.68291771
Iteration 19, loss = 129970418.83475567
Iteration 20, loss = 125207706.84565325
Iteration 21, loss = 120002738.91525960
Iteration 22, loss = 114532548.11745040
Iteration 23, loss = 109059146.54767165
Iteration 24, loss = 103424962.09178202
Iteration 25, loss = 97961426.07849368
Iteration 

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1624: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 10, loss = 153318299.26031998
Iteration 11, loss = 151895072.54418680
Iteration 12, loss = 150133419.18879205
Iteration 13, loss = 148102903.81208953
Iteration 14, loss = 145708843.98039335
Iteration 15, loss = 142906010.69260684
Iteration 16, loss = 139781288.94865042
Iteration 17, loss = 136225360.82345942
Iteration 18, loss = 132240890.55410260
Iteration 19, loss = 128009462.75555572
Iteration 20, loss = 123542208.75431313
Iteration 21, loss = 118580560.86683507
Iteration 22, loss = 113595583.92337108
Iteration 23, loss = 108385387.77743736
Iteration 24, loss = 103099092.53161830
Iteration 25, loss = 97649809.92326392
Iteration 26, loss = 92429753.19660175
Iteration 27, loss = 87580859.45054705
Iteration 28, loss = 82802830.70589939
Iteration 29, loss = 78853403.14008549
Iteration 30, loss = 75382458.86769731
Iteration 31, loss = 72395700.23954022
Iteration 32, loss = 70127914.07847446
Iteration 33, loss = 68262612.80933394
Iteration 34, loss = 66886610.29301711
Iteration 

In [55]:
resultado_rna

array([0.80801432, 0.76356971, 0.75598447, 0.764691  , 0.70046706,
       0.74827031, 0.68840198, 0.82515251, 0.71441949, 0.78281572,
       0.74927869, 0.78430058])

In [56]:
# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado_rna.mean() * 100.0))

Acurácia Média: 75.71%


In [57]:
# Escalonamento 

from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
x_treino_scaler = x_scaler.fit_transform(x_treino)

In [58]:
x_treino_scaler

array([[-1.5330973 , -0.97676557, -0.40713453, -0.89833872, -0.50466988,
        -1.40820029],
       [-0.03364163, -0.97676557,  0.32855417, -0.89833872, -0.50466988,
         1.31322188],
       [ 0.89459283, -0.97676557,  2.56690911,  3.25603402, -0.50466988,
         0.40608116],
       ...,
       [ 0.03776102,  1.02378711, -0.91016269, -0.89833872, -0.50466988,
         0.40608116],
       [-1.46169465,  1.02378711,  0.76659782, -0.89833872, -0.50466988,
        -0.50105957],
       [-0.46205754, -0.97676557, -1.96596021, -0.06746417, -0.50466988,
         1.31322188]])

In [59]:
y_scaler = StandardScaler()
y_treino_scaler = y_scaler.fit_transform(y_treino.reshape(-1,1))

In [60]:
y_treino_scaler

array([[-9.29114569e-01],
       [-6.38651947e-01],
       [-5.39325234e-02],
       [-4.89603748e-01],
       [-6.71349717e-01],
       [-9.67549383e-01],
       [ 1.99311860e+00],
       [-7.49986519e-03],
       [-5.43346082e-01],
       [-2.11871148e-02],
       [-3.93810261e-01],
       [-6.34346126e-02],
       [ 2.99749417e+00],
       [-8.24494558e-01],
       [-4.46162315e-01],
       [ 2.82436277e-01],
       [ 1.14345861e-01],
       [-9.85403479e-01],
       [-5.30554176e-01],
       [-9.27713303e-01],
       [-1.15928290e-01],
       [ 5.03782109e-01],
       [-1.43008068e-01],
       [ 2.33634863e+00],
       [-7.02715735e-01],
       [ 1.74120307e+00],
       [ 2.98421635e-01],
       [-1.89528398e-01],
       [-4.38466738e-01],
       [ 2.63340976e+00],
       [-4.17078733e-01],
       [-7.99784555e-01],
       [-3.51547052e-01],
       [ 4.66138790e-01],
       [ 1.93407799e+00],
       [ 4.94776882e-01],
       [ 1.04631189e+00],
       [ 2.18064123e+00],
       [-7.8

In [61]:
x_teste_scaler = x_scaler.transform(x_teste)
x_teste_scaler

array([[ 0.89459283,  1.02378711, -0.08863026, -0.06746417, -0.50466988,
         1.31322188],
       [ 0.53757957, -0.97676557, -0.22180837, -0.06746417, -0.50466988,
         0.40608116],
       [ 0.60898222,  1.02378711,  1.57449152,  0.76341038,  1.98149332,
        -0.50105957],
       ...,
       [ 1.10880078,  1.02378711,  1.20785059, -0.89833872, -0.50466988,
         0.40608116],
       [ 1.75142463,  1.02378711,  1.34905148, -0.06746417, -0.50466988,
         0.40608116],
       [ 1.60861933, -0.97676557, -0.92299913, -0.89833872, -0.50466988,
         1.31322188]])

In [62]:
y_teste_scaler = y_scaler.transform(y_teste.reshape(-1,1))
y_teste_scaler

array([[-2.95473865e-01],
       [-3.94586401e-01],
       [ 2.73452549e+00],
       [-2.38210314e-02],
       [-3.02234780e-01],
       [-7.35451572e-01],
       [-9.29336992e-01],
       [-1.51272887e-01],
       [-4.79692315e-01],
       [-6.57575321e-01],
       [-5.45730852e-01],
       [-2.30674202e-01],
       [-4.96486983e-01],
       [-7.62000979e-01],
       [ 4.27650930e-01],
       [-2.13097920e-01],
       [-5.97377347e-02],
       [-8.20495396e-01],
       [-5.70591936e-01],
       [ 1.70484300e+00],
       [ 9.04049301e-01],
       [-4.96505360e-02],
       [ 8.26414524e-01],
       [ 8.28086660e-01],
       [-9.73430644e-01],
       [-7.21364344e-01],
       [-8.00107923e-01],
       [-4.67437893e-01],
       [-7.98086955e-01],
       [-4.05891011e-01],
       [-4.35686449e-01],
       [ 3.00977314e+00],
       [-2.13545175e-02],
       [ 6.23001101e-01],
       [ 1.12767486e-01],
       [-7.66007730e-01],
       [-4.11474645e-01],
       [ 3.19710311e+00],
       [ 2.2

In [63]:
redes = MLPRegressor(hidden_layer_sizes=(14,14,14), activation='relu', verbose=True, max_iter=1500,
                    solver='adam', random_state = 12)

In [64]:
redes.fit(x_treino_scaler, y_treino_scaler.ravel())

Iteration 1, loss = 0.71238112
Iteration 2, loss = 0.63561232
Iteration 3, loss = 0.57676505
Iteration 4, loss = 0.52952472
Iteration 5, loss = 0.49229315
Iteration 6, loss = 0.46281878
Iteration 7, loss = 0.43738724
Iteration 8, loss = 0.41516169
Iteration 9, loss = 0.39651974
Iteration 10, loss = 0.37959988
Iteration 11, loss = 0.36435369
Iteration 12, loss = 0.35068319
Iteration 13, loss = 0.33796881
Iteration 14, loss = 0.32579363
Iteration 15, loss = 0.31436045
Iteration 16, loss = 0.30141404
Iteration 17, loss = 0.28851128
Iteration 18, loss = 0.27476969
Iteration 19, loss = 0.25990993
Iteration 20, loss = 0.24399662
Iteration 21, loss = 0.22750189
Iteration 22, loss = 0.21160041
Iteration 23, loss = 0.19675237
Iteration 24, loss = 0.18331089
Iteration 25, loss = 0.17080039
Iteration 26, loss = 0.16045333
Iteration 27, loss = 0.15107943
Iteration 28, loss = 0.14366829
Iteration 29, loss = 0.13753836
Iteration 30, loss = 0.13243805
Iteration 31, loss = 0.12778491
Iteration 32, los

MLPRegressor(hidden_layer_sizes=(14, 14, 14), max_iter=1500, random_state=12,
             verbose=True)

In [65]:
redes.n_layers_

5

In [66]:
redes.score(x_treino_scaler, y_treino_scaler)

0.8677037056914444

In [67]:
# Teste 

redes.score(x_teste_scaler, y_teste_scaler)

0.8765096058889477

In [68]:
previsoes_teste_scaler = redes.predict(x_teste_scaler)

In [69]:
previsoes_teste_scaler

array([-1.52820469e-01, -3.20772476e-01,  2.79510075e+00, -3.38440714e-02,
       -2.19140172e-01, -8.21006043e-01, -7.68654697e-01,  5.07247999e-02,
       -2.63724647e-01, -4.23493862e-01, -4.86800001e-01, -1.45622567e-01,
       -3.29914495e-01, -6.11371422e-01,  6.97012194e-01, -1.16564337e-01,
        7.55396671e-02, -3.31481139e-01, -3.46747701e-01,  1.16456485e+00,
        1.01294838e+00,  2.80309103e-01, -1.81834599e-01,  1.07709763e+00,
       -8.06250334e-01, -5.01575622e-01, -8.24883609e-01, -4.18504195e-01,
       -6.42530635e-01, -1.24423720e-01, -2.76226231e-01,  3.05458554e+00,
        1.77434194e-01, -6.30780453e-02,  1.70534791e-01, -7.07811885e-01,
       -3.14524818e-01,  2.13384429e+00,  2.33046758e+00, -9.38336682e-01,
       -7.17684950e-01, -7.04871413e-01,  8.58666195e-01,  3.06712106e+00,
        2.03151432e+00, -6.64817907e-01, -1.22495372e-01, -3.84455871e-01,
       -7.04936359e-01,  2.38372136e-01, -7.27413682e-01, -3.95800349e-01,
        1.46198297e+00,  

In [70]:
# Métricas 

previsoes_teste_scaler

array([-1.52820469e-01, -3.20772476e-01,  2.79510075e+00, -3.38440714e-02,
       -2.19140172e-01, -8.21006043e-01, -7.68654697e-01,  5.07247999e-02,
       -2.63724647e-01, -4.23493862e-01, -4.86800001e-01, -1.45622567e-01,
       -3.29914495e-01, -6.11371422e-01,  6.97012194e-01, -1.16564337e-01,
        7.55396671e-02, -3.31481139e-01, -3.46747701e-01,  1.16456485e+00,
        1.01294838e+00,  2.80309103e-01, -1.81834599e-01,  1.07709763e+00,
       -8.06250334e-01, -5.01575622e-01, -8.24883609e-01, -4.18504195e-01,
       -6.42530635e-01, -1.24423720e-01, -2.76226231e-01,  3.05458554e+00,
        1.77434194e-01, -6.30780453e-02,  1.70534791e-01, -7.07811885e-01,
       -3.14524818e-01,  2.13384429e+00,  2.33046758e+00, -9.38336682e-01,
       -7.17684950e-01, -7.04871413e-01,  8.58666195e-01,  3.06712106e+00,
        2.03151432e+00, -6.64817907e-01, -1.22495372e-01, -3.84455871e-01,
       -7.04936359e-01,  2.38372136e-01, -7.27413682e-01, -3.95800349e-01,
        1.46198297e+00,  

In [71]:
previsoes_teste_inverse = y_scaler.inverse_transform(previsoes_teste_scaler.reshape(-1,1))

In [72]:
previsoes_teste_inverse

array([[11418.36252786],
       [ 9424.14030962],
       [46421.27866524],
       [12831.06000531],
       [10630.89813781],
       [ 3484.48579724],
       [ 4106.09323295],
       [13835.21068815],
       [10101.51267649],
       [ 8204.45097583],
       [ 7452.7689196 ],
       [11503.82871386],
       [ 9315.59014954],
       [ 5973.63746647],
       [21509.073642  ],
       [11848.85922652],
       [14129.85652558],
       [ 9296.98818363],
       [ 9115.71665863],
       [27060.68279973],
       [25260.4248483 ],
       [16561.24014906],
       [11073.85564797],
       [26022.11773807],
       [ 3659.69157911],
       [ 7277.32671759],
       [ 3438.44449693],
       [ 8263.69710051],
       [ 5603.66037817],
       [11755.53878019],
       [ 9953.07183012],
       [49502.33937907],
       [15339.72792522],
       [12483.94274562],
       [15257.80605966],
       [ 4828.52633451],
       [ 9498.32351464],
       [38569.67652026],
       [40904.33478291],
       [ 2091.32966257],


In [73]:
y_teste

array([[ 9724.53    ],
       [ 8547.6913  ],
       [45702.02235 ],
       [12950.0712  ],
       [ 9644.2525  ],
       [ 4500.33925 ],
       [ 2198.18985 ],
       [11436.73815 ],
       [ 7537.1639  ],
       [ 5425.02335 ],
       [ 6753.038   ],
       [10493.9458  ],
       [ 7337.748   ],
       [ 4185.0979  ],
       [18310.742   ],
       [10702.6424  ],
       [12523.6048  ],
       [ 3490.5491  ],
       [ 6457.8434  ],
       [33475.81715 ],
       [23967.38305 ],
       [12643.3778  ],
       [23045.56616 ],
       [23065.4207  ],
       [ 1674.6323  ],
       [ 4667.60765 ],
       [ 3732.6251  ],
       [ 7682.67    ],
       [ 3756.6216  ],
       [ 8413.46305 ],
       [ 8059.6791  ],
       [48970.2476  ],
       [12979.358   ],
       [20630.28351 ],
       [14571.8908  ],
       [ 4137.5227  ],
       [ 8347.1643  ],
       [51194.55914 ],
       [40003.33225 ],
       [ 1880.487   ],
       [ 5458.04645 ],
       [ 2867.1196  ],
       [20149.3229  ],
       [474

In [74]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [75]:
# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste_inverse)

2817.5843187034125

In [76]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste_inverse))

4437.6736129489

In [77]:
# Revertendo a transformação

x_treino_inverse = x_scaler.inverse_transform(x_treino_scaler)

In [78]:
x_treino_inverse

array([[1.80000000e+01, 0.00000000e+00, 2.82150000e+01, 0.00000000e+00,
        2.77555756e-17, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 3.28000000e+01, 0.00000000e+00,
        2.77555756e-17, 3.00000000e+00],
       [5.20000000e+01, 0.00000000e+00, 4.67500000e+01, 5.00000000e+00,
        2.77555756e-17, 2.00000000e+00],
       ...,
       [4.00000000e+01, 1.00000000e+00, 2.50800000e+01, 0.00000000e+00,
        2.77555756e-17, 2.00000000e+00],
       [1.90000000e+01, 1.00000000e+00, 3.55300000e+01, 0.00000000e+00,
        2.77555756e-17, 1.00000000e+00],
       [3.30000000e+01, 0.00000000e+00, 1.85000000e+01, 1.00000000e+00,
        2.77555756e-17, 3.00000000e+00]])

In [79]:
x_treino

array([[18, 0, 28.215, 0, 0, 0],
       [39, 0, 32.8, 0, 0, 3],
       [52, 0, 46.75, 5, 0, 2],
       ...,
       [40, 1, 25.08, 0, 0, 2],
       [19, 1, 35.53, 0, 0, 1],
       [33, 0, 18.5, 1, 0, 3]], dtype=object)

In [80]:
y_treino_inverse = y_scaler.inverse_transform(y_treino_scaler)

In [81]:
y_treino_inverse

array([[ 2200.83085],
       [ 5649.715  ],
       [12592.5345 ],
       [ 7419.4779 ],
       [ 5261.46945],
       [ 1744.465  ],
       [36898.73308],
       [13143.86485],
       [ 6781.3542 ],
       [12981.3457 ],
       [ 8556.907  ],
       [12479.70895],
       [48824.45   ],
       [ 3443.064  ],
       [ 7935.29115],
       [16586.49771],
       [14590.63205],
       [ 1532.4697 ],
       [ 6933.24225],
       [ 2217.46915],
       [11856.4115 ],
       [19214.70553],
       [11534.87265],
       [40974.1649 ],
       [ 4889.0368 ],
       [33907.548  ],
       [16776.30405],
       [10982.5013 ],
       [ 8026.6666 ],
       [44501.3982 ],
       [ 8280.6227 ],
       [ 3736.4647 ],
       [ 9058.7303 ],
       [18767.7377 ],
       [36197.699  ],
       [19107.7796 ],
       [25656.57526],
       [39125.33225],
       [ 3906.127  ],
       [17085.2676 ],
       [ 3021.80915],
       [36397.576  ],
       [ 4449.462  ],
       [11396.9002 ],
       [ 1622.1885 ],
       [41

In [82]:
x_teste_inverse = x_scaler.inverse_transform(x_teste_scaler)

In [83]:
x_teste_inverse

array([[5.20000000e+01, 1.00000000e+00, 3.02000000e+01, 1.00000000e+00,
        2.77555756e-17, 3.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 2.93700000e+01, 1.00000000e+00,
        2.77555756e-17, 2.00000000e+00],
       [4.80000000e+01, 1.00000000e+00, 4.05650000e+01, 2.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       ...,
       [5.50000000e+01, 1.00000000e+00, 3.82800000e+01, 0.00000000e+00,
        2.77555756e-17, 2.00000000e+00],
       [6.40000000e+01, 1.00000000e+00, 3.91600000e+01, 1.00000000e+00,
        2.77555756e-17, 2.00000000e+00],
       [6.20000000e+01, 0.00000000e+00, 2.50000000e+01, 0.00000000e+00,
        2.77555756e-17, 3.00000000e+00]])

In [84]:
y_teste_inverse = y_scaler.inverse_transform(y_teste_scaler)

In [85]:
y_teste_inverse

array([[ 9724.53    ],
       [ 8547.6913  ],
       [45702.02235 ],
       [12950.0712  ],
       [ 9644.2525  ],
       [ 4500.33925 ],
       [ 2198.18985 ],
       [11436.73815 ],
       [ 7537.1639  ],
       [ 5425.02335 ],
       [ 6753.038   ],
       [10493.9458  ],
       [ 7337.748   ],
       [ 4185.0979  ],
       [18310.742   ],
       [10702.6424  ],
       [12523.6048  ],
       [ 3490.5491  ],
       [ 6457.8434  ],
       [33475.81715 ],
       [23967.38305 ],
       [12643.3778  ],
       [23045.56616 ],
       [23065.4207  ],
       [ 1674.6323  ],
       [ 4667.60765 ],
       [ 3732.6251  ],
       [ 7682.67    ],
       [ 3756.6216  ],
       [ 8413.46305 ],
       [ 8059.6791  ],
       [48970.2476  ],
       [12979.358   ],
       [20630.28351 ],
       [14571.8908  ],
       [ 4137.5227  ],
       [ 8347.1643  ],
       [51194.55914 ],
       [40003.33225 ],
       [ 1880.487   ],
       [ 5458.04645 ],
       [ 2867.1196  ],
       [20149.3229  ],
       [474

In [86]:
y_teste

array([[ 9724.53    ],
       [ 8547.6913  ],
       [45702.02235 ],
       [12950.0712  ],
       [ 9644.2525  ],
       [ 4500.33925 ],
       [ 2198.18985 ],
       [11436.73815 ],
       [ 7537.1639  ],
       [ 5425.02335 ],
       [ 6753.038   ],
       [10493.9458  ],
       [ 7337.748   ],
       [ 4185.0979  ],
       [18310.742   ],
       [10702.6424  ],
       [12523.6048  ],
       [ 3490.5491  ],
       [ 6457.8434  ],
       [33475.81715 ],
       [23967.38305 ],
       [12643.3778  ],
       [23045.56616 ],
       [23065.4207  ],
       [ 1674.6323  ],
       [ 4667.60765 ],
       [ 3732.6251  ],
       [ 7682.67    ],
       [ 3756.6216  ],
       [ 8413.46305 ],
       [ 8059.6791  ],
       [48970.2476  ],
       [12979.358   ],
       [20630.28351 ],
       [14571.8908  ],
       [ 4137.5227  ],
       [ 8347.1643  ],
       [51194.55914 ],
       [40003.33225 ],
       [ 1880.487   ],
       [ 5458.04645 ],
       [ 2867.1196  ],
       [20149.3229  ],
       [474